public class Excecao {
    public static void main(String args[]) {
        
        try {
            int vetor[] = new int [6];
        
            System.out.println ("Inicio da exceção");
        
            vetor[7] = 1;
            
            System.out.println ("Se não o exception não funcionar esta linha será impressa.");
        }
        catch (ArrayIndexOutOfBoundsException exception){
            System.out.println("----Exceção caso o indice informado seja inválido---");
        }
        
        System.out.println ("Após o uso do exception esse texto foi impresso");

    }
}
